package it.unipr.frontend;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import it.unipr.frontend.reg.REGFrontend;
import it.unive.lisa.DefaultConfiguration;
import it.unive.lisa.LiSA;
import it.unive.lisa.conf.LiSAConfiguration;
import it.unive.lisa.program.Program;

import java.io.IOException;

public class Main {

    public static void main(String[] args) throws IOException {
        String file = args[0];
        System.out.println("File: " + file);

        Program program = REGFrontend.processFile(args[0]);
        LiSAConfiguration conf = new DefaultConfiguration();

        conf.workdir = "./outputs/reg";
        conf.analysisGraphs = LiSAConfiguration.GraphType.HTML;
        conf.serializeResults = true;

        LiSA lisa = new LiSA(conf);
        lisa.run(program);
    }

}
