package it.unipr.frontend;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import it.unipr.frontend.reg.REGCodeMemberVisitor;
import it.unipr.reg.antlr.RegLexer;
import it.unipr.reg.antlr.RegParser;
import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

public class Main {
   
	public static void main(String[] args) throws IOException {
		String file = args[0];
		System.out.println("File: " + file);
		File fn = new File(file);
		InputStream inputFile = new FileInputStream(fn);
        CharStream input = CharStreams.fromStream(inputFile);
		RegLexer lexer = new RegLexer(input);
		CommonTokenStream tokens = new CommonTokenStream(lexer);
		RegParser parser = new RegParser(tokens);

		ParseTree tree = parser.program();

		REGCodeMemberVisitor visitor = new REGCodeMemberVisitor();

		visitor.visit(tree);
	}

}
